### ISSUE TITLE
StratLan tracker integration

### ISSUE THREAD

**Issue by Telluur** [SlapGaming/SlapBot#25]
Pull the Lan planning information from Google Sheets
- [x] Format the sheets
- [ ] Pull data google API
- [ ] X days to next lan notifier
- [ ] Lan dates commands
- [ ] Confirmed Attendees list
